#!/bin/sh

appDir=$(cd $(dirname $0); pwd)

$appDir/clean
$appDir/make $*

exitCode=$?

if [ $exitCode -ne 0 ]; then
    exit $exitCode
fi

echo "[[[Packaging OpenCOR...]]]"

origDir=`pwd`

cd $appDir/build

cpack

exitCode=$?

cd $origDir

if [ $exitCode -eq 0 ]; then
    echo "[[[All done!]]]"
fi

exit $exitCode
