#!/bin/sh

echo "[[[Running OpenCOR...]]]"

appDir=$(cd $(dirname $0); pwd)

if [ "`uname -s`" = "Linux" ]; then
    appExe=$appDir/build/bin/OpenCOR
else
    appExe=$appDir/build/OpenCOR.app/Contents/MacOS/OpenCOR
fi

if [ -f $appExe ]; then
    $appExe "$@"
else
    echo "OpenCOR must first be built before being run."
fi

echo "[[[All done!]]]"
