#!/bin/sh

echo "[[[Running OpenCOR's tests...]]]"

appDir=$(cd $(dirname $0); pwd)

if [ "`uname -s`" = "Linux" ]; then
    appTestsExe=$appDir/build/bin/runtests
else
    appTestsExe=$appDir/build/OpenCOR.app/Contents/MacOS/runtests
fi

if [ -f $appTestsExe ]; then
    $appTestsExe "$@"
else
    echo "OpenCOR's tests must first be built before being run."
fi

echo "[[[All done!]]]"
