#!/bin/sh

if [ "$1" = "all" ]; then
    echo "[[[Cleaning all of OpenCOR...]]]"
else
    echo "[[[Cleaning OpenCOR...]]]"
fi

appDir=$(cd $(dirname $0); pwd)/..

rm -fr $appDir/build/.clang-tidy $appDir/build/.ninja* $appDir/build/* > /dev/null 2>&1

if [ "$1" = "all" ]; then
    rm -fr $appDir/ext/* > /dev/null 2>&1
fi

echo "[[[All done!]]]"
