name: CD

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  cd:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-2019
          - name: Linux
            os: ubuntu-20.04
          - name: macOS
            os: macos-13
    env:
      BUILDCACHE_COMPRESS_FORMAT: ZSTD
      BUILDCACHE_DEBUG: -1
      BUILDCACHE_DIRECT_MODE: true
      BUILDCACHE_LOG_FILE: ""
      EV_CERTIFICATE_BASE64: ${{ secrets.EV_CERTIFICATE_BASE64 }}
      DEVELOPER_ID_APPLICATION_CERTIFICATE_DESCRIPTION: ${{ secrets.DEVELOPER_ID_APPLICATION_CERTIFICATE_DESCRIPTION }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    steps:
      - name: Set the timezone to New Zealand
        uses: szenius/set-timezone@v2.0
        with:
          timezoneWindows: "New Zealand Standard Time"
          timezoneLinux: "Pacific/Auckland"
          timezoneMacos: "Pacific/Auckland"
      - name: Check out OpenCOR
        uses: actions/checkout@v4
      - name: Retrieve the EV certificate (Windows only)
        if: matrix.name == 'Windows'
        shell: bash
        run: echo -n $EV_CERTIFICATE_BASE64 | base64 -d > EVCertificate.pfx
      - name: Retrieve some environment variales for code signing and notarisation (macOS only)
        if: runner.os == 'macOS'
        run: |
          echo "DEVELOPER_ID_APPLICATION_CERTIFICATE_DESCRIPTION=$(echo $DEVELOPER_ID_APPLICATION_CERTIFICATE_DESCRIPTION)" >> $GITHUB_ENV
          echo "APPLE_ID=$(echo $APPLE_ID)" >> $GITHUB_ENV
          echo "APPLE_APP_SPECIFIC_PASSWORD=$(echo $APPLE_APP_SPECIFIC_PASSWORD)" >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=$(echo $APPLE_TEAM_ID)" >> $GITHUB_ENV
      - name: Import the Developer ID Application certificate (macOS only)
        if: runner.os == 'macOS'
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.DEVELOPER_ID_APPLICATION_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.DEVELOPER_ID_APPLICATION_CERTIFICATE_PASSWORD }}
      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Sphinx
        run: pip install Sphinx sphinx_copybutton sphinx_inline_tabs
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.12.12'
          setup-python: 'false'
      - name: Install packages (Linux only)
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt install libglu1-mesa
      - name: Install buildcache
        uses: cscouto/buildcache-action@v1
        with:
          cache_key: ${{ matrix.os }}
      - name: Cache external dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/ext
          key: ${{ matrix.os }}-ExternalDependencies-${{ github.sha }}
          restore-keys: ${{ matrix.os }}-ExternalDependencies
      - name: Package OpenCOR
        run: ./package
      - name: Upload OpenCOR artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ./build/OpenCOR-*
      - name: Release OpenCOR
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/OpenCOR-*
